/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 .\\Car.glb
*/

import React, {
    useEffect,
    useRef,
    useState
} from 'react'
import {
    Box,
    useGLTF
} from '@react-three/drei'
import {
    useWheels
} from "./useWheels.jsx";
import {
    useBox,
    useRaycastVehicle
} from "@react-three/cannon";
import {
    useControls
} from "./useControls.jsx";
import {
    useFrame
} from "@react-three/fiber";
import {
    Wheel
} from "./Wheel.jsx";
import {
    PlayerCamera
} from "./PlayerCamera.jsx";
import {
    Color,
    Vector3
} from "three";
import {
    TireParticles
} from "./TireParticles.jsx";

export function Car(props) {
    const {
        nodes,
        materials
    } = useGLTF('/Car.glb')
    
    const [shouldUpdate, setShouldUpdate] = useState(false);
    
    
    const {isCameraFollow} = props;

    const position = [1200.5, 2.5, -300];
    const width = 2.15;
    const height = 1;
    const front = 2.3;
    const wheelRadius = 0.9;

    const chassisBodyArgs = [width, height, front * 2];
    const [chassisBody, chassisApi] = useBox(
        () => ({
            allowSleep: true,
            sleepSpeedLimit: 1,
            args: chassisBodyArgs,
            mass: 2800,
            position,
            collisionFilterGroup: 1,
            collisionFilterMask: 80
        }),
        useRef(null),
    );

    const [wheels, wheelInfos] = useWheels(width, height, front, wheelRadius);

    const [vehicle, vehicleApi] = useRaycastVehicle(
        () => ({
            chassisBody,
            wheelInfos,
            wheels
        }),
        useRef(null),
    );


    const carPosition = useRef([0, 0, 0]);
    const velocity = useRef(new Vector3(0, 0, 0));
    const velocityLength = useRef(0);
    const rotation = useRef([0, 0, 0]);

    useControls(vehicleApi, chassisApi, position, velocityLength);
    
    useEffect(() => {
        chassisApi.position.subscribe(pos => {
            carPosition.current = pos;
            setShouldUpdate(!shouldUpdate)
        });
        chassisApi.velocity.subscribe(vel => {
            velocity.current.x = vel[0];
            velocity.current.y = vel[1];
            velocity.current.z = vel[2];
            velocityLength.current = velocity.current.length();
        });
        chassisApi.rotation.subscribe(rot => rotation.current = rot);
        props.setPlayerRef(carPosition);
    }, [])

    return (
        <group
            ref={vehicle} {...props}
            dispose={null}>
            <group ref={chassisBody}>
                <mesh
                position={props.offset}
                receiveShadow
                castShadow
                geometry={nodes.Cylinder005_4.geometry}
                material={materials.Car}/>
                <mesh
                    position={props.offset}
                    receiveShadow
                    castShadow
                    geometry={nodes.Cube.geometry}
                    material={materials.mETAL}/>
            </group>
            <Wheel
                wheelRef={wheels[0]}
                radius={wheelRadius}/>
            <Wheel
                wheelRef={wheels[1]}
                radius={wheelRadius}/>
            <Wheel
                wheelRef={wheels[2]}
                radius={wheelRadius}/>
            <Wheel
                wheelRef={wheels[3]}
                radius={wheelRadius}/>
            
            <PlayerCamera
                active={isCameraFollow}
                position={carPosition}
                velocity={velocity}
                velocityLength={velocityLength}></PlayerCamera>
        </group>
    )
}

useGLTF.preload('/Car.glb')
