/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 .\\CornDestroyed.glb
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function CornShrub(props) {
  const { nodes, materials } = useGLTF('/CornShrub.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[0, 0, 1.71]}>
        <mesh geometry={nodes.Circle005.geometry} material={materials['Material.001']} />
        <mesh geometry={nodes.Circle005_1.geometry} material={materials['Material.001']} />
      </group>
    </group>
  )
}

useGLTF.preload('/CornShrub.glb')
