/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 .\\CornPlant.glb
*/

import React, {
    useRef
} from 'react'
import {
    useGLTF
} from '@react-three/drei'

export function CornPlant(props) {
    const {
        nodes,
        materials
    } = useGLTF('/CornPlant.glb')

    const cornPlantVariation = props.variation;

    return (
        <group {...props}
               dispose={null}>
            {cornPlantVariation === 1 &&
                <group>
                    <mesh
                        geometry={nodes.Circle001.geometry}
                        material={materials['Material.001']}/>
                    <mesh
                        geometry={nodes.Circle001_1.geometry}
                        material={materials['Material.003']}/>
                </group>}
            {cornPlantVariation === 2 &&
                <group>
                    <mesh
                        geometry={nodes.Circle002.geometry}
                        material={materials['Material.001']}/>
                    <mesh
                        geometry={nodes.Circle002_1.geometry}
                        material={materials['Material.003']}/>
                </group>}
            {cornPlantVariation === 3 &&
                <group>
                    <mesh
                        geometry={nodes.Circle003.geometry}
                        material={materials['Material.001']}/>
                    <mesh
                        geometry={nodes.Circle003_1.geometry}
                        material={materials['Material.003']}/>
                </group>}
            {cornPlantVariation === 4 &&
                <group>
                    <mesh
                        geometry={nodes.Circle004.geometry}
                        material={materials['Material.001']}/>
                    <mesh
                        geometry={nodes.Circle004_1.geometry}
                        material={materials['Material.003']}/>
                </group>}
        </group>
    )
}

useGLTF.preload('/CornPlant.glb')
