/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 .\\Cornfield.glb
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function CornField(props) {
  const { nodes, materials } = useGLTF('/Cornfield.glb')
  return (
    <group {...props}>
      <mesh receiveShadow castShadow geometry={nodes.Cornfield.geometry} material={materials['Material.001']} />
    </group>
  )
}

useGLTF.preload('/Cornfield.glb')
