/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 .\\CornFieldGroundFirst.glb
*/

import React, {
    useRef
} from 'react'
import {
    useGLTF
} from '@react-three/drei'
import * as CANNON
    from "cannon";
import {
    useTrimesh
} from "@react-three/cannon";

export function CornFieldGroundFirst(props) {
    const {
        nodes,
        materials
    } = useGLTF('/CornFieldGroundFirst.glb')

    const vertices = nodes.Plane007.geometry.attributes.position.array;
    const indices = nodes.Plane007.geometry.index.array;

    const slipperyMaterial = new CANNON.Material('slippery');
    slipperyMaterial.friction = 0;

    const [collider] = useTrimesh(() => ({
        args: [vertices, indices],
        mass: 0,
        type: "Dynamic",
        collisionFilterGroup: 2,
        material: slipperyMaterial
    }));

    return (
        <group {...props}
               dispose={null}>
            <mesh
                geometry={nodes.Plane007.geometry}
                material={materials.Grass}/>
        </group>
    )
}

useGLTF.preload('/CornFieldGroundFirst.glb')
