/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 .\\Cornfield.glb
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function CornField(props) {
  const { nodes, materials } = useGLTF('/Cornfield.glb')
  return (
    <group {...props} dispose={null}>
      <mesh castShadow receiveShadow geometry={nodes.Plane006.geometry} material={materials['Material.001']} />
      <mesh castShadow receiveShadow geometry={nodes.Plane006_1.geometry} material={materials['Material.003']} />
    </group>
  )
}

useGLTF.preload('/Cornfield.glb')
