/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 .\\Island.glb
*/

import React, {
    useEffect,
    useMemo,
    useRef,
    useState
} from 'react'
import {
    Box,
    useGLTF
} from '@react-three/drei'
import {
    useBox,
    useConvexPolyhedron,
    useTrimesh
} from "@react-three/cannon";
import * as THREE
    from 'three';
import * as CANNON
    from "cannon";
import {
    MeshSurfaceSampler
} from "three/addons/math/MeshSurfaceSampler.js";
import {
    CornFieldArea
} from "./CornFieldArea.jsx";

export function Island(props) {
    const {
        nodes,
        materials
    } = useGLTF('/Island.glb')
    
    const vertices = nodes.Cube.geometry.attributes.position.array;
    const indices = nodes.Cube.geometry.index.array;

    const slipperyMaterial = new CANNON.Material('slippery');
    slipperyMaterial.friction = 0;

    const [collider] = useTrimesh(() => ({
        args: [vertices, indices],
        mass: 0,
        type: "Dynamic",
        collisionFilterGroup: 2,
        material: slipperyMaterial
    }));

    return (
        <group {...props}
               dispose={null}>
            <mesh
                ref={collider}
                geometry={nodes.Cube.geometry}
                material={materials.Material}/>
        </group>
    )
}

useGLTF.preload('/Island.glb')
