/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 .\\jungleGround.glb
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function JungleGround(props) {
  const { nodes, materials } = useGLTF('/jungleGround.glb')
  return (
    <group {...props} dispose={null}>
      <mesh receiveShadow castShadow geometry={nodes.Plane.geometry} material={materials.Ground} />
    </group>
  )
}

useGLTF.preload('/jungleGround.glb')
