/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 .\\jungletree.glb
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function JungleTree(props) {
  const { nodes, materials } = useGLTF('/jungletree.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Cylinder.geometry} material={materials.TreeTrunk} />
      <mesh geometry={nodes.Cylinder_1.geometry} material={materials.Leaves} />
    </group>
  )
}

useGLTF.preload('/jungletree.glb')
